package kr.ch.oe.dao;

import java.util.List;
import kr.ch.oe.model.Attend;
import kr.ch.oe.model.AttendExample;
import org.apache.ibatis.annotations.Param;

public interface AttendMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int countByExample(AttendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int deleteByExample(AttendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int deleteByPrimaryKey(Long attendSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int insert(Attend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int insertSelective(Attend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	List<Attend> selectByExample(AttendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	Attend selectByPrimaryKey(Long attendSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByExampleSelective(@Param("record") Attend record,
			@Param("example") AttendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByExample(@Param("record") Attend record,
			@Param("example") AttendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByPrimaryKeySelective(Attend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByPrimaryKey(Attend record);
}