package kr.ch.oe.dao;

import java.util.List;
import kr.ch.oe.model.AttendItem;
import kr.ch.oe.model.AttendItemExample;
import org.apache.ibatis.annotations.Param;

public interface AttendItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int countByExample(AttendItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int deleteByExample(AttendItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int deleteByPrimaryKey(Long attendItemSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int insert(AttendItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int insertSelective(AttendItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	List<AttendItem> selectByExampleWithBLOBs(AttendItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	List<AttendItem> selectByExample(AttendItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	AttendItem selectByPrimaryKey(Long attendItemSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByExampleSelective(@Param("record") AttendItem record,
			@Param("example") AttendItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") AttendItem record,
			@Param("example") AttendItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByExample(@Param("record") AttendItem record,
			@Param("example") AttendItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByPrimaryKeySelective(AttendItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(AttendItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attend_item
	 * @mbggenerated  Sun Jun 21 17:35:04 KST 2015
	 */
	int updateByPrimaryKey(AttendItem record);
}