package kr.ch.oe.dao;

import java.util.List;
import kr.ch.oe.model.AttendItemMngr;
import kr.ch.oe.model.AttendItemMngrExample;
import org.apache.ibatis.annotations.Param;

public interface AttendItemMngrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int countByExample(AttendItemMngrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int deleteByExample(AttendItemMngrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int deleteByPrimaryKey(Long attendItemMngrSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int insert(AttendItemMngr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int insertSelective(AttendItemMngr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    List<AttendItemMngr> selectByExampleWithBLOBs(AttendItemMngrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    List<AttendItemMngr> selectByExample(AttendItemMngrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    AttendItemMngr selectByPrimaryKey(Long attendItemMngrSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int updateByExampleSelective(@Param("record") AttendItemMngr record, @Param("example") AttendItemMngrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") AttendItemMngr record, @Param("example") AttendItemMngrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int updateByExample(@Param("record") AttendItemMngr record, @Param("example") AttendItemMngrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int updateByPrimaryKeySelective(AttendItemMngr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int updateByPrimaryKeyWithBLOBs(AttendItemMngr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attend_item_mngr
     *
     * @mbggenerated Sun Jun 21 17:35:04 KST 2015
     */
    int updateByPrimaryKey(AttendItemMngr record);
}