package kr.ch.oe.dao;

import java.util.List;
import kr.ch.oe.model.DepartmentChangeHist;
import kr.ch.oe.model.DepartmentChangeHistExample;
import org.apache.ibatis.annotations.Param;

public interface DepartmentChangeHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int countByExample(DepartmentChangeHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int deleteByExample(DepartmentChangeHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int deleteByPrimaryKey(Long departmentChangeHistSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int insert(DepartmentChangeHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int insertSelective(DepartmentChangeHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    List<DepartmentChangeHist> selectByExample(DepartmentChangeHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    DepartmentChangeHist selectByPrimaryKey(Long departmentChangeHistSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int updateByExampleSelective(@Param("record") DepartmentChangeHist record, @Param("example") DepartmentChangeHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int updateByExample(@Param("record") DepartmentChangeHist record, @Param("example") DepartmentChangeHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int updateByPrimaryKeySelective(DepartmentChangeHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_change_hist
     *
     * @mbggenerated Sun May 31 14:14:53 KST 2015
     */
    int updateByPrimaryKey(DepartmentChangeHist record);
}