package kr.ch.oe.dao;

import java.util.List;
import kr.ch.oe.model.EduStatus;
import kr.ch.oe.model.EduStatusExample;
import org.apache.ibatis.annotations.Param;

public interface EduStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int countByExample(EduStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int deleteByExample(EduStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int deleteByPrimaryKey(Long eduStatusSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int insert(EduStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int insertSelective(EduStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    List<EduStatus> selectByExample(EduStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    EduStatus selectByPrimaryKey(Long eduStatusSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int updateByExampleSelective(@Param("record") EduStatus record, @Param("example") EduStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int updateByExample(@Param("record") EduStatus record, @Param("example") EduStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int updateByPrimaryKeySelective(EduStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_status
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    int updateByPrimaryKey(EduStatus record);
}