package kr.ch.oe.dao;

import java.util.List;
import kr.ch.oe.model.RoleChangeHist;
import kr.ch.oe.model.RoleChangeHistExample;
import org.apache.ibatis.annotations.Param;

public interface RoleChangeHistMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int countByExample(RoleChangeHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int deleteByExample(RoleChangeHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int deleteByPrimaryKey(Long roleChangeHistSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int insert(RoleChangeHist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int insertSelective(RoleChangeHist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	List<RoleChangeHist> selectByExample(RoleChangeHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	RoleChangeHist selectByPrimaryKey(Long roleChangeHistSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int updateByExampleSelective(@Param("record") RoleChangeHist record,
			@Param("example") RoleChangeHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int updateByExample(@Param("record") RoleChangeHist record,
			@Param("example") RoleChangeHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int updateByPrimaryKeySelective(RoleChangeHist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_change_hist
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	int updateByPrimaryKey(RoleChangeHist record);
}