package kr.ch.oe.dao;

import java.util.List;
import kr.ch.oe.model.StudyStatus;
import kr.ch.oe.model.StudyStatusExample;
import org.apache.ibatis.annotations.Param;

public interface StudyStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int countByExample(StudyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int deleteByExample(StudyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int deleteByPrimaryKey(Long studyStatusSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int insert(StudyStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int insertSelective(StudyStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    List<StudyStatus> selectByExample(StudyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    StudyStatus selectByPrimaryKey(Long studyStatusSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int updateByExampleSelective(@Param("record") StudyStatus record, @Param("example") StudyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int updateByExample(@Param("record") StudyStatus record, @Param("example") StudyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int updateByPrimaryKeySelective(StudyStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_status
     *
     * @mbggenerated Mon Jan 26 10:06:48 KST 2015
     */
    int updateByPrimaryKey(StudyStatus record);
}