package kr.ch.oe.model;

import java.util.Date;

public class AttendWorship {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.attend_worship_seq
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private Long attendWorshipSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.weeks
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private Long weeks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.worship_seq
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private Long worshipSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.worship_times
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private Integer worshipTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.worship_date
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private String worshipDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.user_id
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.reg_id
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private String regId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attend_worship.reg_time
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.attend_worship_seq
	 * @return  the value of attend_worship.attend_worship_seq
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public Long getAttendWorshipSeq() {
		return attendWorshipSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.attend_worship_seq
	 * @param attendWorshipSeq  the value for attend_worship.attend_worship_seq
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setAttendWorshipSeq(Long attendWorshipSeq) {
		this.attendWorshipSeq = attendWorshipSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.weeks
	 * @return  the value of attend_worship.weeks
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public Long getWeeks() {
		return weeks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.weeks
	 * @param weeks  the value for attend_worship.weeks
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setWeeks(Long weeks) {
		this.weeks = weeks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.worship_seq
	 * @return  the value of attend_worship.worship_seq
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public Long getWorshipSeq() {
		return worshipSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.worship_seq
	 * @param worshipSeq  the value for attend_worship.worship_seq
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setWorshipSeq(Long worshipSeq) {
		this.worshipSeq = worshipSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.worship_times
	 * @return  the value of attend_worship.worship_times
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public Integer getWorshipTimes() {
		return worshipTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.worship_times
	 * @param worshipTimes  the value for attend_worship.worship_times
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setWorshipTimes(Integer worshipTimes) {
		this.worshipTimes = worshipTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.worship_date
	 * @return  the value of attend_worship.worship_date
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public String getWorshipDate() {
		return worshipDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.worship_date
	 * @param worshipDate  the value for attend_worship.worship_date
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setWorshipDate(String worshipDate) {
		this.worshipDate = worshipDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.user_id
	 * @return  the value of attend_worship.user_id
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.user_id
	 * @param userId  the value for attend_worship.user_id
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.reg_id
	 * @return  the value of attend_worship.reg_id
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public String getRegId() {
		return regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.reg_id
	 * @param regId  the value for attend_worship.reg_id
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setRegId(String regId) {
		this.regId = regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attend_worship.reg_time
	 * @return  the value of attend_worship.reg_time
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attend_worship.reg_time
	 * @param regTime  the value for attend_worship.reg_time
	 * @mbggenerated  Sun Jun 14 14:51:40 KST 2015
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
}