package kr.ch.oe.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DepartmentExample {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	protected List<Criteria> oredCriteria;


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public DepartmentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDeptSeqIsNull() {
			addCriterion("dept_seq is null");
			return (Criteria) this;
		}

		public Criteria andDeptSeqIsNotNull() {
			addCriterion("dept_seq is not null");
			return (Criteria) this;
		}

		public Criteria andDeptSeqEqualTo(Long value) {
			addCriterion("dept_seq =", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqNotEqualTo(Long value) {
			addCriterion("dept_seq <>", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqGreaterThan(Long value) {
			addCriterion("dept_seq >", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("dept_seq >=", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqLessThan(Long value) {
			addCriterion("dept_seq <", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqLessThanOrEqualTo(Long value) {
			addCriterion("dept_seq <=", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqIn(List<Long> values) {
			addCriterion("dept_seq in", values, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqNotIn(List<Long> values) {
			addCriterion("dept_seq not in", values, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqBetween(Long value1, Long value2) {
			addCriterion("dept_seq between", value1, value2, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqNotBetween(Long value1, Long value2) {
			addCriterion("dept_seq not between", value1, value2, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptNameIsNull() {
			addCriterion("dept_name is null");
			return (Criteria) this;
		}

		public Criteria andDeptNameIsNotNull() {
			addCriterion("dept_name is not null");
			return (Criteria) this;
		}

		public Criteria andDeptNameEqualTo(String value) {
			addCriterion("dept_name =", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameNotEqualTo(String value) {
			addCriterion("dept_name <>", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameGreaterThan(String value) {
			addCriterion("dept_name >", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameGreaterThanOrEqualTo(String value) {
			addCriterion("dept_name >=", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameLessThan(String value) {
			addCriterion("dept_name <", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameLessThanOrEqualTo(String value) {
			addCriterion("dept_name <=", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameLike(String value) {
			addCriterion("dept_name like", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameNotLike(String value) {
			addCriterion("dept_name not like", value, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameIn(List<String> values) {
			addCriterion("dept_name in", values, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameNotIn(List<String> values) {
			addCriterion("dept_name not in", values, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameBetween(String value1, String value2) {
			addCriterion("dept_name between", value1, value2, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptNameNotBetween(String value1, String value2) {
			addCriterion("dept_name not between", value1, value2, "deptName");
			return (Criteria) this;
		}

		public Criteria andDeptTypeIsNull() {
			addCriterion("dept_type is null");
			return (Criteria) this;
		}

		public Criteria andDeptTypeIsNotNull() {
			addCriterion("dept_type is not null");
			return (Criteria) this;
		}

		public Criteria andDeptTypeEqualTo(String value) {
			addCriterion("dept_type =", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeNotEqualTo(String value) {
			addCriterion("dept_type <>", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeGreaterThan(String value) {
			addCriterion("dept_type >", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeGreaterThanOrEqualTo(String value) {
			addCriterion("dept_type >=", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeLessThan(String value) {
			addCriterion("dept_type <", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeLessThanOrEqualTo(String value) {
			addCriterion("dept_type <=", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeLike(String value) {
			addCriterion("dept_type like", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeNotLike(String value) {
			addCriterion("dept_type not like", value, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeIn(List<String> values) {
			addCriterion("dept_type in", values, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeNotIn(List<String> values) {
			addCriterion("dept_type not in", values, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeBetween(String value1, String value2) {
			addCriterion("dept_type between", value1, value2, "deptType");
			return (Criteria) this;
		}

		public Criteria andDeptTypeNotBetween(String value1, String value2) {
			addCriterion("dept_type not between", value1, value2, "deptType");
			return (Criteria) this;
		}

		public Criteria andLeaderIdIsNull() {
			addCriterion("leader_id is null");
			return (Criteria) this;
		}

		public Criteria andLeaderIdIsNotNull() {
			addCriterion("leader_id is not null");
			return (Criteria) this;
		}

		public Criteria andLeaderIdEqualTo(String value) {
			addCriterion("leader_id =", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdNotEqualTo(String value) {
			addCriterion("leader_id <>", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdGreaterThan(String value) {
			addCriterion("leader_id >", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdGreaterThanOrEqualTo(String value) {
			addCriterion("leader_id >=", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdLessThan(String value) {
			addCriterion("leader_id <", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdLessThanOrEqualTo(String value) {
			addCriterion("leader_id <=", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdLike(String value) {
			addCriterion("leader_id like", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdNotLike(String value) {
			addCriterion("leader_id not like", value, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdIn(List<String> values) {
			addCriterion("leader_id in", values, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdNotIn(List<String> values) {
			addCriterion("leader_id not in", values, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdBetween(String value1, String value2) {
			addCriterion("leader_id between", value1, value2, "leaderId");
			return (Criteria) this;
		}

		public Criteria andLeaderIdNotBetween(String value1, String value2) {
			addCriterion("leader_id not between", value1, value2, "leaderId");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andParentSeqIsNull() {
			addCriterion("parent_seq is null");
			return (Criteria) this;
		}

		public Criteria andParentSeqIsNotNull() {
			addCriterion("parent_seq is not null");
			return (Criteria) this;
		}

		public Criteria andParentSeqEqualTo(Long value) {
			addCriterion("parent_seq =", value, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqNotEqualTo(Long value) {
			addCriterion("parent_seq <>", value, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqGreaterThan(Long value) {
			addCriterion("parent_seq >", value, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("parent_seq >=", value, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqLessThan(Long value) {
			addCriterion("parent_seq <", value, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqLessThanOrEqualTo(Long value) {
			addCriterion("parent_seq <=", value, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqIn(List<Long> values) {
			addCriterion("parent_seq in", values, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqNotIn(List<Long> values) {
			addCriterion("parent_seq not in", values, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqBetween(Long value1, Long value2) {
			addCriterion("parent_seq between", value1, value2, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andParentSeqNotBetween(Long value1, Long value2) {
			addCriterion("parent_seq not between", value1, value2, "parentSeq");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNull() {
			addCriterion("reg_time is null");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNotNull() {
			addCriterion("reg_time is not null");
			return (Criteria) this;
		}

		public Criteria andRegTimeEqualTo(Date value) {
			addCriterion("reg_time =", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotEqualTo(Date value) {
			addCriterion("reg_time <>", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThan(Date value) {
			addCriterion("reg_time >", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_time >=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThan(Date value) {
			addCriterion("reg_time <", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThanOrEqualTo(Date value) {
			addCriterion("reg_time <=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeIn(List<Date> values) {
			addCriterion("reg_time in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotIn(List<Date> values) {
			addCriterion("reg_time not in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeBetween(Date value1, Date value2) {
			addCriterion("reg_time between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotBetween(Date value1, Date value2) {
			addCriterion("reg_time not between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIsNull() {
			addCriterion("is_deleted is null");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIsNotNull() {
			addCriterion("is_deleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsDeletedEqualTo(String value) {
			addCriterion("is_deleted =", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotEqualTo(String value) {
			addCriterion("is_deleted <>", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedGreaterThan(String value) {
			addCriterion("is_deleted >", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
			addCriterion("is_deleted >=", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedLessThan(String value) {
			addCriterion("is_deleted <", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedLessThanOrEqualTo(String value) {
			addCriterion("is_deleted <=", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedLike(String value) {
			addCriterion("is_deleted like", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotLike(String value) {
			addCriterion("is_deleted not like", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIn(List<String> values) {
			addCriterion("is_deleted in", values, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotIn(List<String> values) {
			addCriterion("is_deleted not in", values, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedBetween(String value1, String value2) {
			addCriterion("is_deleted between", value1, value2, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotBetween(String value1, String value2) {
			addCriterion("is_deleted not between", value1, value2, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeIsNull() {
			addCriterion("deleted_time is null");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeIsNotNull() {
			addCriterion("deleted_time is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeEqualTo(Date value) {
			addCriterion("deleted_time =", value, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeNotEqualTo(Date value) {
			addCriterion("deleted_time <>", value, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeGreaterThan(Date value) {
			addCriterion("deleted_time >", value, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("deleted_time >=", value, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeLessThan(Date value) {
			addCriterion("deleted_time <", value, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeLessThanOrEqualTo(Date value) {
			addCriterion("deleted_time <=", value, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeIn(List<Date> values) {
			addCriterion("deleted_time in", values, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeNotIn(List<Date> values) {
			addCriterion("deleted_time not in", values, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeBetween(Date value1, Date value2) {
			addCriterion("deleted_time between", value1, value2, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDeletedTimeNotBetween(Date value1, Date value2) {
			addCriterion("deleted_time not between", value1, value2, "deletedTime");
			return (Criteria) this;
		}

		public Criteria andDepth1IsNull() {
			addCriterion("depth1 is null");
			return (Criteria) this;
		}

		public Criteria andDepth1IsNotNull() {
			addCriterion("depth1 is not null");
			return (Criteria) this;
		}

		public Criteria andDepth1EqualTo(Integer value) {
			addCriterion("depth1 =", value, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1NotEqualTo(Integer value) {
			addCriterion("depth1 <>", value, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1GreaterThan(Integer value) {
			addCriterion("depth1 >", value, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1GreaterThanOrEqualTo(Integer value) {
			addCriterion("depth1 >=", value, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1LessThan(Integer value) {
			addCriterion("depth1 <", value, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1LessThanOrEqualTo(Integer value) {
			addCriterion("depth1 <=", value, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1In(List<Integer> values) {
			addCriterion("depth1 in", values, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1NotIn(List<Integer> values) {
			addCriterion("depth1 not in", values, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1Between(Integer value1, Integer value2) {
			addCriterion("depth1 between", value1, value2, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth1NotBetween(Integer value1, Integer value2) {
			addCriterion("depth1 not between", value1, value2, "depth1");
			return (Criteria) this;
		}

		public Criteria andDepth2IsNull() {
			addCriterion("depth2 is null");
			return (Criteria) this;
		}

		public Criteria andDepth2IsNotNull() {
			addCriterion("depth2 is not null");
			return (Criteria) this;
		}

		public Criteria andDepth2EqualTo(Integer value) {
			addCriterion("depth2 =", value, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2NotEqualTo(Integer value) {
			addCriterion("depth2 <>", value, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2GreaterThan(Integer value) {
			addCriterion("depth2 >", value, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2GreaterThanOrEqualTo(Integer value) {
			addCriterion("depth2 >=", value, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2LessThan(Integer value) {
			addCriterion("depth2 <", value, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2LessThanOrEqualTo(Integer value) {
			addCriterion("depth2 <=", value, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2In(List<Integer> values) {
			addCriterion("depth2 in", values, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2NotIn(List<Integer> values) {
			addCriterion("depth2 not in", values, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2Between(Integer value1, Integer value2) {
			addCriterion("depth2 between", value1, value2, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth2NotBetween(Integer value1, Integer value2) {
			addCriterion("depth2 not between", value1, value2, "depth2");
			return (Criteria) this;
		}

		public Criteria andDepth3IsNull() {
			addCriterion("depth3 is null");
			return (Criteria) this;
		}

		public Criteria andDepth3IsNotNull() {
			addCriterion("depth3 is not null");
			return (Criteria) this;
		}

		public Criteria andDepth3EqualTo(Integer value) {
			addCriterion("depth3 =", value, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3NotEqualTo(Integer value) {
			addCriterion("depth3 <>", value, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3GreaterThan(Integer value) {
			addCriterion("depth3 >", value, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3GreaterThanOrEqualTo(Integer value) {
			addCriterion("depth3 >=", value, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3LessThan(Integer value) {
			addCriterion("depth3 <", value, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3LessThanOrEqualTo(Integer value) {
			addCriterion("depth3 <=", value, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3In(List<Integer> values) {
			addCriterion("depth3 in", values, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3NotIn(List<Integer> values) {
			addCriterion("depth3 not in", values, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3Between(Integer value1, Integer value2) {
			addCriterion("depth3 between", value1, value2, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth3NotBetween(Integer value1, Integer value2) {
			addCriterion("depth3 not between", value1, value2, "depth3");
			return (Criteria) this;
		}

		public Criteria andDepth4IsNull() {
			addCriterion("depth4 is null");
			return (Criteria) this;
		}

		public Criteria andDepth4IsNotNull() {
			addCriterion("depth4 is not null");
			return (Criteria) this;
		}

		public Criteria andDepth4EqualTo(Integer value) {
			addCriterion("depth4 =", value, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4NotEqualTo(Integer value) {
			addCriterion("depth4 <>", value, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4GreaterThan(Integer value) {
			addCriterion("depth4 >", value, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4GreaterThanOrEqualTo(Integer value) {
			addCriterion("depth4 >=", value, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4LessThan(Integer value) {
			addCriterion("depth4 <", value, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4LessThanOrEqualTo(Integer value) {
			addCriterion("depth4 <=", value, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4In(List<Integer> values) {
			addCriterion("depth4 in", values, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4NotIn(List<Integer> values) {
			addCriterion("depth4 not in", values, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4Between(Integer value1, Integer value2) {
			addCriterion("depth4 between", value1, value2, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth4NotBetween(Integer value1, Integer value2) {
			addCriterion("depth4 not between", value1, value2, "depth4");
			return (Criteria) this;
		}

		public Criteria andDepth5IsNull() {
			addCriterion("depth5 is null");
			return (Criteria) this;
		}

		public Criteria andDepth5IsNotNull() {
			addCriterion("depth5 is not null");
			return (Criteria) this;
		}

		public Criteria andDepth5EqualTo(Integer value) {
			addCriterion("depth5 =", value, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5NotEqualTo(Integer value) {
			addCriterion("depth5 <>", value, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5GreaterThan(Integer value) {
			addCriterion("depth5 >", value, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5GreaterThanOrEqualTo(Integer value) {
			addCriterion("depth5 >=", value, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5LessThan(Integer value) {
			addCriterion("depth5 <", value, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5LessThanOrEqualTo(Integer value) {
			addCriterion("depth5 <=", value, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5In(List<Integer> values) {
			addCriterion("depth5 in", values, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5NotIn(List<Integer> values) {
			addCriterion("depth5 not in", values, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5Between(Integer value1, Integer value2) {
			addCriterion("depth5 between", value1, value2, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepth5NotBetween(Integer value1, Integer value2) {
			addCriterion("depth5 not between", value1, value2, "depth5");
			return (Criteria) this;
		}

		public Criteria andDepthIsNull() {
			addCriterion("depth is null");
			return (Criteria) this;
		}

		public Criteria andDepthIsNotNull() {
			addCriterion("depth is not null");
			return (Criteria) this;
		}

		public Criteria andDepthEqualTo(Byte value) {
			addCriterion("depth =", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthNotEqualTo(Byte value) {
			addCriterion("depth <>", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthGreaterThan(Byte value) {
			addCriterion("depth >", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthGreaterThanOrEqualTo(Byte value) {
			addCriterion("depth >=", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthLessThan(Byte value) {
			addCriterion("depth <", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthLessThanOrEqualTo(Byte value) {
			addCriterion("depth <=", value, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthIn(List<Byte> values) {
			addCriterion("depth in", values, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthNotIn(List<Byte> values) {
			addCriterion("depth not in", values, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthBetween(Byte value1, Byte value2) {
			addCriterion("depth between", value1, value2, "depth");
			return (Criteria) this;
		}

		public Criteria andDepthNotBetween(Byte value1, Byte value2) {
			addCriterion("depth not between", value1, value2, "depth");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table department
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	protected String limitByClause;
	
	
	public String getLimitByClause() {
		return limitByClause;
	}

	public void setLimitByClause(String limitByClause) {
		this.limitByClause = limitByClause;
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table department
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 08 10:31:21 KST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}