package kr.ch.oe.model;

import java.util.Date;

public class Department {
	
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dept_seq
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	private Long deptSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dept_name
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	private String deptName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dept_type
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	private String deptType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.leader_id
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	private String leaderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.desc
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	private String desc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.parent_seq
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	private Long parentSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.reg_time
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	private Date regTime;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dept_seq
	 * @return  the value of department.dept_seq
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public Long getDeptSeq() {
		return deptSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dept_seq
	 * @param deptSeq  the value for department.dept_seq
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public void setDeptSeq(Long deptSeq) {
		this.deptSeq = deptSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dept_name
	 * @return  the value of department.dept_name
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dept_name
	 * @param deptName  the value for department.dept_name
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dept_type
	 * @return  the value of department.dept_type
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public String getDeptType() {
		return deptType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dept_type
	 * @param deptType  the value for department.dept_type
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public void setDeptType(String deptType) {
		this.deptType = deptType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.leader_id
	 * @return  the value of department.leader_id
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public String getLeaderId() {
		return leaderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.leader_id
	 * @param leaderId  the value for department.leader_id
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public void setLeaderId(String leaderId) {
		this.leaderId = leaderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.desc
	 * @return  the value of department.desc
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.desc
	 * @param desc  the value for department.desc
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.parent_seq
	 * @return  the value of department.parent_seq
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public Long getParentSeq() {
		return parentSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.parent_seq
	 * @param parentSeq  the value for department.parent_seq
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public void setParentSeq(Long parentSeq) {
		this.parentSeq = parentSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.reg_time
	 * @return  the value of department.reg_time
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.reg_time
	 * @param regTime  the value for department.reg_time
	 * @mbggenerated  Sun Mar 08 17:47:15 KST 2015
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	@Override
	public String toString() {
		return "Department [deptSeq=" + deptSeq + ", deptName=" + deptName
				+ ", parentSeq=" + parentSeq + ", regTime=" + regTime + "]";
	}

    
    private Department parent;
	public Department getParent() {
		return parent;
	}

	public void setParent(Department parent) {
		this.parent = parent;
	}

}