package kr.ch.oe.model;

import java.util.Date;

public class EduStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.edu_status_seq
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private Long eduStatusSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.user_id
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.edu_seq
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private Long eduSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.edu_date
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private String eduDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.edu_unit
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private Integer eduUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.state
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.reg_id
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_status.reg_time
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.edu_status_seq
     *
     * @return the value of edu_status.edu_status_seq
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public Long getEduStatusSeq() {
        return eduStatusSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.edu_status_seq
     *
     * @param eduStatusSeq the value for edu_status.edu_status_seq
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setEduStatusSeq(Long eduStatusSeq) {
        this.eduStatusSeq = eduStatusSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.user_id
     *
     * @return the value of edu_status.user_id
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.user_id
     *
     * @param userId the value for edu_status.user_id
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.edu_seq
     *
     * @return the value of edu_status.edu_seq
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public Long getEduSeq() {
        return eduSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.edu_seq
     *
     * @param eduSeq the value for edu_status.edu_seq
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setEduSeq(Long eduSeq) {
        this.eduSeq = eduSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.edu_date
     *
     * @return the value of edu_status.edu_date
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public String getEduDate() {
        return eduDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.edu_date
     *
     * @param eduDate the value for edu_status.edu_date
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setEduDate(String eduDate) {
        this.eduDate = eduDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.edu_unit
     *
     * @return the value of edu_status.edu_unit
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public Integer getEduUnit() {
        return eduUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.edu_unit
     *
     * @param eduUnit the value for edu_status.edu_unit
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setEduUnit(Integer eduUnit) {
        this.eduUnit = eduUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.state
     *
     * @return the value of edu_status.state
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.state
     *
     * @param state the value for edu_status.state
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.reg_id
     *
     * @return the value of edu_status.reg_id
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.reg_id
     *
     * @param regId the value for edu_status.reg_id
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setRegId(String regId) {
        this.regId = regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_status.reg_time
     *
     * @return the value of edu_status.reg_time
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_status.reg_time
     *
     * @param regTime the value for edu_status.reg_time
     *
     * @mbggenerated Tue Jan 27 21:36:55 KST 2015
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}