package kr.ch.oe.model;

import java.util.Date;

public class RoleChangeHist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.role_change_hist_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private Long roleChangeHistSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.user_id
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.before_role_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private Long beforeRoleSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.after_role_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private Long afterRoleSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.change_date
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private String changeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.change_resn
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private String changeResn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.reg_id
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private String regId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_change_hist.reg_time
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.role_change_hist_seq
	 * @return  the value of role_change_hist.role_change_hist_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public Long getRoleChangeHistSeq() {
		return roleChangeHistSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.role_change_hist_seq
	 * @param roleChangeHistSeq  the value for role_change_hist.role_change_hist_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setRoleChangeHistSeq(Long roleChangeHistSeq) {
		this.roleChangeHistSeq = roleChangeHistSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.user_id
	 * @return  the value of role_change_hist.user_id
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.user_id
	 * @param userId  the value for role_change_hist.user_id
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.before_role_seq
	 * @return  the value of role_change_hist.before_role_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public Long getBeforeRoleSeq() {
		return beforeRoleSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.before_role_seq
	 * @param beforeRoleSeq  the value for role_change_hist.before_role_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setBeforeRoleSeq(Long beforeRoleSeq) {
		this.beforeRoleSeq = beforeRoleSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.after_role_seq
	 * @return  the value of role_change_hist.after_role_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public Long getAfterRoleSeq() {
		return afterRoleSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.after_role_seq
	 * @param afterRoleSeq  the value for role_change_hist.after_role_seq
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setAfterRoleSeq(Long afterRoleSeq) {
		this.afterRoleSeq = afterRoleSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.change_date
	 * @return  the value of role_change_hist.change_date
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public String getChangeDate() {
		return changeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.change_date
	 * @param changeDate  the value for role_change_hist.change_date
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setChangeDate(String changeDate) {
		this.changeDate = changeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.change_resn
	 * @return  the value of role_change_hist.change_resn
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public String getChangeResn() {
		return changeResn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.change_resn
	 * @param changeResn  the value for role_change_hist.change_resn
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setChangeResn(String changeResn) {
		this.changeResn = changeResn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.reg_id
	 * @return  the value of role_change_hist.reg_id
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public String getRegId() {
		return regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.reg_id
	 * @param regId  the value for role_change_hist.reg_id
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setRegId(String regId) {
		this.regId = regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_change_hist.reg_time
	 * @return  the value of role_change_hist.reg_time
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_change_hist.reg_time
	 * @param regTime  the value for role_change_hist.reg_time
	 * @mbggenerated  Sun May 31 16:33:26 KST 2015
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
}