package kr.ch.oe.model;

import java.util.Date;
import java.util.List;

/**
 * 사용자(담임목사, 대교구장, 교구장, 목자, 목장원, 새신자 등)
 * 
 * @author gusfot
 *
 */
public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private Long userSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.reg_dt
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String regDt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.addr
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String addr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.cell_phone
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String cellPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.home_phone
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String homePhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.job
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String job;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.birth
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String birth;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.dept_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private Long deptSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.academic
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String academic;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.major
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String major;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private Long roleSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.flag
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String flag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.reg_time
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private Date regTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.is_deleted
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private String isDeleted;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.deleted_time
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	private Date deletedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_seq
	 * @return  the value of user.user_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public Long getUserSeq() {
		return userSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_seq
	 * @param userSeq  the value for user.user_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setUserSeq(Long userSeq) {
		this.userSeq = userSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_name
	 * @return  the value of user.user_name
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_name
	 * @param userName  the value for user.user_name
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.reg_dt
	 * @return  the value of user.reg_dt
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getRegDt() {
		return regDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.reg_dt
	 * @param regDt  the value for user.reg_dt
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setRegDt(String regDt) {
		this.regDt = regDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.addr
	 * @return  the value of user.addr
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.addr
	 * @param addr  the value for user.addr
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.cell_phone
	 * @return  the value of user.cell_phone
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getCellPhone() {
		return cellPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.cell_phone
	 * @param cellPhone  the value for user.cell_phone
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.home_phone
	 * @return  the value of user.home_phone
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getHomePhone() {
		return homePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.home_phone
	 * @param homePhone  the value for user.home_phone
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.job
	 * @return  the value of user.job
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.job
	 * @param job  the value for user.job
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.birth
	 * @return  the value of user.birth
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getBirth() {
		return birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.birth
	 * @param birth  the value for user.birth
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setBirth(String birth) {
		this.birth = birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.dept_seq
	 * @return  the value of user.dept_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public Long getDeptSeq() {
		return deptSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.dept_seq
	 * @param deptSeq  the value for user.dept_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setDeptSeq(Long deptSeq) {
		this.deptSeq = deptSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.academic
	 * @return  the value of user.academic
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getAcademic() {
		return academic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.academic
	 * @param academic  the value for user.academic
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setAcademic(String academic) {
		this.academic = academic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.major
	 * @return  the value of user.major
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getMajor() {
		return major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.major
	 * @param major  the value for user.major
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setMajor(String major) {
		this.major = major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role_seq
	 * @return  the value of user.role_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public Long getRoleSeq() {
		return roleSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role_seq
	 * @param roleSeq  the value for user.role_seq
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setRoleSeq(Long roleSeq) {
		this.roleSeq = roleSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.flag
	 * @return  the value of user.flag
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.flag
	 * @param flag  the value for user.flag
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.reg_time
	 * @return  the value of user.reg_time
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.reg_time
	 * @param regTime  the value for user.reg_time
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.is_deleted
	 * @return  the value of user.is_deleted
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public String getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.is_deleted
	 * @param isDeleted  the value for user.is_deleted
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.deleted_time
	 * @return  the value of user.deleted_time
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public Date getDeletedTime() {
		return deletedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.deleted_time
	 * @param deletedTime  the value for user.deleted_time
	 * @mbg.generated  Sun Dec 04 12:25:24 KST 2016
	 */
	public void setDeletedTime(Date deletedTime) {
		this.deletedTime = deletedTime;
	}

	/**
	 * 금주 점수
	 */
	private int thisWeekPoint;

	/**
	 * 누적 점수
	 */
	private int allPoint;
	/**
	 * 권한정보
	 */
	private Role role;
	/**
	 * 소속 정보
	 */
	private Department department;

	/**
	 * 전도현황 목록
	 */
	private List<MissionWorkStatus> missionWorkStatusList;

	/**
	 * 양육현황 목록
	 */
	private List<EduStatus> eduStatusList;
	

	/**
	 * 해당직분
	 */
	private String roleName;

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public List<MissionWorkStatus> getMissionWorkStatusList() {
		return missionWorkStatusList;
	}

	public void setMissionWorkList(List<MissionWorkStatus> missionWorkStatusList) {
		this.missionWorkStatusList = missionWorkStatusList;
	}

	public List<EduStatus> getEduStatusList() {
		return eduStatusList;
	}

	public void setEduStatusListList(List<EduStatus> eduStatusList) {
		this.eduStatusList = eduStatusList;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public int getThisWeekPoint() {
		return thisWeekPoint;
	}

	public void setThisWeekPoint(int thisWeekPoint) {
		this.thisWeekPoint = thisWeekPoint;
	}

	public int getAllPoint() {
		return allPoint;
	}

	public void setAllPoint(int allPoint) {
		this.allPoint = allPoint;
	}

}