package kr.ch.oe.model;

import java.util.Date;

public class Worship {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worship.worship_seq
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	private Integer worshipSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worship.worship_name
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	private String worshipName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worship.worship_day
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	private String worshipDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worship.reg_id
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	private String regId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worship.reg_time
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worship.worship_seq
	 * @return  the value of worship.worship_seq
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public Integer getWorshipSeq() {
		return worshipSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worship.worship_seq
	 * @param worshipSeq  the value for worship.worship_seq
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public void setWorshipSeq(Integer worshipSeq) {
		this.worshipSeq = worshipSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worship.worship_name
	 * @return  the value of worship.worship_name
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public String getWorshipName() {
		return worshipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worship.worship_name
	 * @param worshipName  the value for worship.worship_name
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public void setWorshipName(String worshipName) {
		this.worshipName = worshipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worship.worship_day
	 * @return  the value of worship.worship_day
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public String getWorshipDay() {
		return worshipDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worship.worship_day
	 * @param worshipDay  the value for worship.worship_day
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public void setWorshipDay(String worshipDay) {
		this.worshipDay = worshipDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worship.reg_id
	 * @return  the value of worship.reg_id
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public String getRegId() {
		return regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worship.reg_id
	 * @param regId  the value for worship.reg_id
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public void setRegId(String regId) {
		this.regId = regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worship.reg_time
	 * @return  the value of worship.reg_time
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worship.reg_time
	 * @param regTime  the value for worship.reg_time
	 * @mbggenerated  Sun Jun 14 14:33:40 KST 2015
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
}