package kr.ch.oe.model;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_seq
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    private Long noticeSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.openYn
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    private String openYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.reg_id
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.reg_time
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_seq
     *
     * @return the value of notice.notice_seq
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public Long getNoticeSeq() {
        return noticeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_seq
     *
     * @param noticeSeq the value for notice.notice_seq
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public void setNoticeSeq(Long noticeSeq) {
        this.noticeSeq = noticeSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.openYn
     *
     * @return the value of notice.openYn
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public String getOpenYn() {
        return openYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.openYn
     *
     * @param openYn the value for notice.openYn
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public void setOpenYn(String openYn) {
        this.openYn = openYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.reg_id
     *
     * @return the value of notice.reg_id
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.reg_id
     *
     * @param regId the value for notice.reg_id
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public void setRegId(String regId) {
        this.regId = regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.reg_time
     *
     * @return the value of notice.reg_time
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.reg_time
     *
     * @param regTime the value for notice.reg_time
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbggenerated Tue Jan 27 21:33:38 KST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}