package kr.ch.oe.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReportExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public ReportExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andReportSeqIsNull() {
			addCriterion("report_seq is null");
			return (Criteria) this;
		}

		public Criteria andReportSeqIsNotNull() {
			addCriterion("report_seq is not null");
			return (Criteria) this;
		}

		public Criteria andReportSeqEqualTo(Long value) {
			addCriterion("report_seq =", value, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqNotEqualTo(Long value) {
			addCriterion("report_seq <>", value, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqGreaterThan(Long value) {
			addCriterion("report_seq >", value, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("report_seq >=", value, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqLessThan(Long value) {
			addCriterion("report_seq <", value, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqLessThanOrEqualTo(Long value) {
			addCriterion("report_seq <=", value, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqIn(List<Long> values) {
			addCriterion("report_seq in", values, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqNotIn(List<Long> values) {
			addCriterion("report_seq not in", values, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqBetween(Long value1, Long value2) {
			addCriterion("report_seq between", value1, value2, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andReportSeqNotBetween(Long value1, Long value2) {
			addCriterion("report_seq not between", value1, value2, "reportSeq");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andDeptSeqIsNull() {
			addCriterion("dept_seq is null");
			return (Criteria) this;
		}

		public Criteria andDeptSeqIsNotNull() {
			addCriterion("dept_seq is not null");
			return (Criteria) this;
		}

		public Criteria andDeptSeqEqualTo(Long value) {
			addCriterion("dept_seq =", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqNotEqualTo(Long value) {
			addCriterion("dept_seq <>", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqGreaterThan(Long value) {
			addCriterion("dept_seq >", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("dept_seq >=", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqLessThan(Long value) {
			addCriterion("dept_seq <", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqLessThanOrEqualTo(Long value) {
			addCriterion("dept_seq <=", value, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqIn(List<Long> values) {
			addCriterion("dept_seq in", values, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqNotIn(List<Long> values) {
			addCriterion("dept_seq not in", values, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqBetween(Long value1, Long value2) {
			addCriterion("dept_seq between", value1, value2, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andDeptSeqNotBetween(Long value1, Long value2) {
			addCriterion("dept_seq not between", value1, value2, "deptSeq");
			return (Criteria) this;
		}

		public Criteria andWeeksIsNull() {
			addCriterion("weeks is null");
			return (Criteria) this;
		}

		public Criteria andWeeksIsNotNull() {
			addCriterion("weeks is not null");
			return (Criteria) this;
		}

		public Criteria andWeeksEqualTo(Integer value) {
			addCriterion("weeks =", value, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksNotEqualTo(Integer value) {
			addCriterion("weeks <>", value, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksGreaterThan(Integer value) {
			addCriterion("weeks >", value, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksGreaterThanOrEqualTo(Integer value) {
			addCriterion("weeks >=", value, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksLessThan(Integer value) {
			addCriterion("weeks <", value, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksLessThanOrEqualTo(Integer value) {
			addCriterion("weeks <=", value, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksIn(List<Integer> values) {
			addCriterion("weeks in", values, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksNotIn(List<Integer> values) {
			addCriterion("weeks not in", values, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksBetween(Integer value1, Integer value2) {
			addCriterion("weeks between", value1, value2, "weeks");
			return (Criteria) this;
		}

		public Criteria andWeeksNotBetween(Integer value1, Integer value2) {
			addCriterion("weeks not between", value1, value2, "weeks");
			return (Criteria) this;
		}

		public Criteria andVisitContentIsNull() {
			addCriterion("visit_content is null");
			return (Criteria) this;
		}

		public Criteria andVisitContentIsNotNull() {
			addCriterion("visit_content is not null");
			return (Criteria) this;
		}

		public Criteria andVisitContentEqualTo(Long value) {
			addCriterion("visit_content =", value, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentNotEqualTo(Long value) {
			addCriterion("visit_content <>", value, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentGreaterThan(Long value) {
			addCriterion("visit_content >", value, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentGreaterThanOrEqualTo(Long value) {
			addCriterion("visit_content >=", value, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentLessThan(Long value) {
			addCriterion("visit_content <", value, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentLessThanOrEqualTo(Long value) {
			addCriterion("visit_content <=", value, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentIn(List<Long> values) {
			addCriterion("visit_content in", values, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentNotIn(List<Long> values) {
			addCriterion("visit_content not in", values, "visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentBetween(Long value1, Long value2) {
			addCriterion("visit_content between", value1, value2,
					"visitContent");
			return (Criteria) this;
		}

		public Criteria andVisitContentNotBetween(Long value1, Long value2) {
			addCriterion("visit_content not between", value1, value2,
					"visitContent");
			return (Criteria) this;
		}

		public Criteria andPointIsNull() {
			addCriterion("point is null");
			return (Criteria) this;
		}

		public Criteria andPointIsNotNull() {
			addCriterion("point is not null");
			return (Criteria) this;
		}

		public Criteria andPointEqualTo(Short value) {
			addCriterion("point =", value, "point");
			return (Criteria) this;
		}

		public Criteria andPointNotEqualTo(Short value) {
			addCriterion("point <>", value, "point");
			return (Criteria) this;
		}

		public Criteria andPointGreaterThan(Short value) {
			addCriterion("point >", value, "point");
			return (Criteria) this;
		}

		public Criteria andPointGreaterThanOrEqualTo(Short value) {
			addCriterion("point >=", value, "point");
			return (Criteria) this;
		}

		public Criteria andPointLessThan(Short value) {
			addCriterion("point <", value, "point");
			return (Criteria) this;
		}

		public Criteria andPointLessThanOrEqualTo(Short value) {
			addCriterion("point <=", value, "point");
			return (Criteria) this;
		}

		public Criteria andPointIn(List<Short> values) {
			addCriterion("point in", values, "point");
			return (Criteria) this;
		}

		public Criteria andPointNotIn(List<Short> values) {
			addCriterion("point not in", values, "point");
			return (Criteria) this;
		}

		public Criteria andPointBetween(Short value1, Short value2) {
			addCriterion("point between", value1, value2, "point");
			return (Criteria) this;
		}

		public Criteria andPointNotBetween(Short value1, Short value2) {
			addCriterion("point not between", value1, value2, "point");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqIsNull() {
			addCriterion("mokjang_report_seq is null");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqIsNotNull() {
			addCriterion("mokjang_report_seq is not null");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqEqualTo(Long value) {
			addCriterion("mokjang_report_seq =", value, "mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqNotEqualTo(Long value) {
			addCriterion("mokjang_report_seq <>", value, "mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqGreaterThan(Long value) {
			addCriterion("mokjang_report_seq >", value, "mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("mokjang_report_seq >=", value, "mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqLessThan(Long value) {
			addCriterion("mokjang_report_seq <", value, "mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqLessThanOrEqualTo(Long value) {
			addCriterion("mokjang_report_seq <=", value, "mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqIn(List<Long> values) {
			addCriterion("mokjang_report_seq in", values, "mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqNotIn(List<Long> values) {
			addCriterion("mokjang_report_seq not in", values,
					"mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqBetween(Long value1, Long value2) {
			addCriterion("mokjang_report_seq between", value1, value2,
					"mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andMokjangReportSeqNotBetween(Long value1, Long value2) {
			addCriterion("mokjang_report_seq not between", value1, value2,
					"mokjangReportSeq");
			return (Criteria) this;
		}

		public Criteria andRegIdIsNull() {
			addCriterion("reg_id is null");
			return (Criteria) this;
		}

		public Criteria andRegIdIsNotNull() {
			addCriterion("reg_id is not null");
			return (Criteria) this;
		}

		public Criteria andRegIdEqualTo(String value) {
			addCriterion("reg_id =", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotEqualTo(String value) {
			addCriterion("reg_id <>", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdGreaterThan(String value) {
			addCriterion("reg_id >", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdGreaterThanOrEqualTo(String value) {
			addCriterion("reg_id >=", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLessThan(String value) {
			addCriterion("reg_id <", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLessThanOrEqualTo(String value) {
			addCriterion("reg_id <=", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLike(String value) {
			addCriterion("reg_id like", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotLike(String value) {
			addCriterion("reg_id not like", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdIn(List<String> values) {
			addCriterion("reg_id in", values, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotIn(List<String> values) {
			addCriterion("reg_id not in", values, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdBetween(String value1, String value2) {
			addCriterion("reg_id between", value1, value2, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotBetween(String value1, String value2) {
			addCriterion("reg_id not between", value1, value2, "regId");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNull() {
			addCriterion("reg_time is null");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNotNull() {
			addCriterion("reg_time is not null");
			return (Criteria) this;
		}

		public Criteria andRegTimeEqualTo(Date value) {
			addCriterion("reg_time =", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotEqualTo(Date value) {
			addCriterion("reg_time <>", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThan(Date value) {
			addCriterion("reg_time >", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_time >=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThan(Date value) {
			addCriterion("reg_time <", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThanOrEqualTo(Date value) {
			addCriterion("reg_time <=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeIn(List<Date> values) {
			addCriterion("reg_time in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotIn(List<Date> values) {
			addCriterion("reg_time not in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeBetween(Date value1, Date value2) {
			addCriterion("reg_time between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotBetween(Date value1, Date value2) {
			addCriterion("reg_time not between", value1, value2, "regTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table report
	 * @mbggenerated  Thu May 07 18:35:52 KST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 11 17:04:50 KST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}