package kr.ch.oe.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReportItemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public ReportItemsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReportItemsSeqIsNull() {
            addCriterion("report_items_seq is null");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqIsNotNull() {
            addCriterion("report_items_seq is not null");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqEqualTo(Long value) {
            addCriterion("report_items_seq =", value, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqNotEqualTo(Long value) {
            addCriterion("report_items_seq <>", value, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqGreaterThan(Long value) {
            addCriterion("report_items_seq >", value, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("report_items_seq >=", value, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqLessThan(Long value) {
            addCriterion("report_items_seq <", value, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqLessThanOrEqualTo(Long value) {
            addCriterion("report_items_seq <=", value, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqIn(List<Long> values) {
            addCriterion("report_items_seq in", values, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqNotIn(List<Long> values) {
            addCriterion("report_items_seq not in", values, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqBetween(Long value1, Long value2) {
            addCriterion("report_items_seq between", value1, value2, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsSeqNotBetween(Long value1, Long value2) {
            addCriterion("report_items_seq not between", value1, value2, "reportItemsSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeIsNull() {
            addCriterion("report_items_code is null");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeIsNotNull() {
            addCriterion("report_items_code is not null");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeEqualTo(String value) {
            addCriterion("report_items_code =", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeNotEqualTo(String value) {
            addCriterion("report_items_code <>", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeGreaterThan(String value) {
            addCriterion("report_items_code >", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("report_items_code >=", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeLessThan(String value) {
            addCriterion("report_items_code <", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeLessThanOrEqualTo(String value) {
            addCriterion("report_items_code <=", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeLike(String value) {
            addCriterion("report_items_code like", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeNotLike(String value) {
            addCriterion("report_items_code not like", value, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeIn(List<String> values) {
            addCriterion("report_items_code in", values, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeNotIn(List<String> values) {
            addCriterion("report_items_code not in", values, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeBetween(String value1, String value2) {
            addCriterion("report_items_code between", value1, value2, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsCodeNotBetween(String value1, String value2) {
            addCriterion("report_items_code not between", value1, value2, "reportItemsCode");
            return (Criteria) this;
        }

        public Criteria andReportItemsIsNull() {
            addCriterion("report_items is null");
            return (Criteria) this;
        }

        public Criteria andReportItemsIsNotNull() {
            addCriterion("report_items is not null");
            return (Criteria) this;
        }

        public Criteria andReportItemsEqualTo(Long value) {
            addCriterion("report_items =", value, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsNotEqualTo(Long value) {
            addCriterion("report_items <>", value, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsGreaterThan(Long value) {
            addCriterion("report_items >", value, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsGreaterThanOrEqualTo(Long value) {
            addCriterion("report_items >=", value, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsLessThan(Long value) {
            addCriterion("report_items <", value, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsLessThanOrEqualTo(Long value) {
            addCriterion("report_items <=", value, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsIn(List<Long> values) {
            addCriterion("report_items in", values, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsNotIn(List<Long> values) {
            addCriterion("report_items not in", values, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsBetween(Long value1, Long value2) {
            addCriterion("report_items between", value1, value2, "reportItems");
            return (Criteria) this;
        }

        public Criteria andReportItemsNotBetween(Long value1, Long value2) {
            addCriterion("report_items not between", value1, value2, "reportItems");
            return (Criteria) this;
        }

        public Criteria andUseFlagIsNull() {
            addCriterion("use_flag is null");
            return (Criteria) this;
        }

        public Criteria andUseFlagIsNotNull() {
            addCriterion("use_flag is not null");
            return (Criteria) this;
        }

        public Criteria andUseFlagEqualTo(String value) {
            addCriterion("use_flag =", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotEqualTo(String value) {
            addCriterion("use_flag <>", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagGreaterThan(String value) {
            addCriterion("use_flag >", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagGreaterThanOrEqualTo(String value) {
            addCriterion("use_flag >=", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagLessThan(String value) {
            addCriterion("use_flag <", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagLessThanOrEqualTo(String value) {
            addCriterion("use_flag <=", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagLike(String value) {
            addCriterion("use_flag like", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotLike(String value) {
            addCriterion("use_flag not like", value, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagIn(List<String> values) {
            addCriterion("use_flag in", values, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotIn(List<String> values) {
            addCriterion("use_flag not in", values, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagBetween(String value1, String value2) {
            addCriterion("use_flag between", value1, value2, "useFlag");
            return (Criteria) this;
        }

        public Criteria andUseFlagNotBetween(String value1, String value2) {
            addCriterion("use_flag not between", value1, value2, "useFlag");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNull() {
            addCriterion("reg_id is null");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNotNull() {
            addCriterion("reg_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegIdEqualTo(String value) {
            addCriterion("reg_id =", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotEqualTo(String value) {
            addCriterion("reg_id <>", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThan(String value) {
            addCriterion("reg_id >", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThanOrEqualTo(String value) {
            addCriterion("reg_id >=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThan(String value) {
            addCriterion("reg_id <", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThanOrEqualTo(String value) {
            addCriterion("reg_id <=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLike(String value) {
            addCriterion("reg_id like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotLike(String value) {
            addCriterion("reg_id not like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdIn(List<String> values) {
            addCriterion("reg_id in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotIn(List<String> values) {
            addCriterion("reg_id not in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdBetween(String value1, String value2) {
            addCriterion("reg_id between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotBetween(String value1, String value2) {
            addCriterion("reg_id not between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNull() {
            addCriterion("reg_time is null");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNotNull() {
            addCriterion("reg_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegTimeEqualTo(Date value) {
            addCriterion("reg_time =", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotEqualTo(Date value) {
            addCriterion("reg_time <>", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThan(Date value) {
            addCriterion("reg_time >", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("reg_time >=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThan(Date value) {
            addCriterion("reg_time <", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThanOrEqualTo(Date value) {
            addCriterion("reg_time <=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeIn(List<Date> values) {
            addCriterion("reg_time in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotIn(List<Date> values) {
            addCriterion("reg_time not in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeBetween(Date value1, Date value2) {
            addCriterion("reg_time between", value1, value2, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotBetween(Date value1, Date value2) {
            addCriterion("reg_time not between", value1, value2, "regTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_items
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 22 14:28:40 KST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}