package kr.ch.oe.model;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_seq
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private Long reportSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.weeks
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private Integer weeks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.worship_dt
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private String worshipDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.worship_place
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private String worshipPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.offering
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private Long offering;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.total_score
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private Long totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.dept_seq
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private Long deptSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reg_id
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reg_time
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_seq
     *
     * @return the value of report.report_seq
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public Long getReportSeq() {
        return reportSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_seq
     *
     * @param reportSeq the value for report.report_seq
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setReportSeq(Long reportSeq) {
        this.reportSeq = reportSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.weeks
     *
     * @return the value of report.weeks
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public Integer getWeeks() {
        return weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.weeks
     *
     * @param weeks the value for report.weeks
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setWeeks(Integer weeks) {
        this.weeks = weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.worship_dt
     *
     * @return the value of report.worship_dt
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public String getWorshipDt() {
        return worshipDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.worship_dt
     *
     * @param worshipDt the value for report.worship_dt
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setWorshipDt(String worshipDt) {
        this.worshipDt = worshipDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.worship_place
     *
     * @return the value of report.worship_place
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public String getWorshipPlace() {
        return worshipPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.worship_place
     *
     * @param worshipPlace the value for report.worship_place
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setWorshipPlace(String worshipPlace) {
        this.worshipPlace = worshipPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.offering
     *
     * @return the value of report.offering
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public Long getOffering() {
        return offering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.offering
     *
     * @param offering the value for report.offering
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setOffering(Long offering) {
        this.offering = offering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.total_score
     *
     * @return the value of report.total_score
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public Long getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.total_score
     *
     * @param totalScore the value for report.total_score
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setTotalScore(Long totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.dept_seq
     *
     * @return the value of report.dept_seq
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public Long getDeptSeq() {
        return deptSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.dept_seq
     *
     * @param deptSeq the value for report.dept_seq
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setDeptSeq(Long deptSeq) {
        this.deptSeq = deptSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reg_id
     *
     * @return the value of report.reg_id
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reg_id
     *
     * @param regId the value for report.reg_id
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setRegId(String regId) {
        this.regId = regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reg_time
     *
     * @return the value of report.reg_time
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reg_time
     *
     * @param regTime the value for report.reg_time
     *
     * @mbggenerated Sun Jan 11 17:04:50 KST 2015
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}