package kr.ch.oe.model;

import java.util.Date;

public class ReportItemMngr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item_mngr.report_item_mngr_seq
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private Long reportItemMngrSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item_mngr.item_name
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item_mngr.item_weight
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private Integer itemweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item_mngr.use_flag
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private String useFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item_mngr.reg_id
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item_mngr.reg_time
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_item_mngr.item_desc
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private String itemDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item_mngr.report_item_mngr_seq
     *
     * @return the value of report_item_mngr.report_item_mngr_seq
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Long getReportItemMngrSeq() {
        return reportItemMngrSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item_mngr.report_item_mngr_seq
     *
     * @param reportItemMngrSeq the value for report_item_mngr.report_item_mngr_seq
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setReportItemMngrSeq(Long reportItemMngrSeq) {
        this.reportItemMngrSeq = reportItemMngrSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item_mngr.item_name
     *
     * @return the value of report_item_mngr.item_name
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item_mngr.item_name
     *
     * @param itemName the value for report_item_mngr.item_name
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item_mngr.item_weight
     *
     * @return the value of report_item_mngr.item_weight
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Integer getItemweight() {
        return itemweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item_mngr.item_weight
     *
     * @param itemweight the value for report_item_mngr.item_weight
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setItemweight(Integer itemweight) {
        this.itemweight = itemweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item_mngr.use_flag
     *
     * @return the value of report_item_mngr.use_flag
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item_mngr.use_flag
     *
     * @param useFlag the value for report_item_mngr.use_flag
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item_mngr.reg_id
     *
     * @return the value of report_item_mngr.reg_id
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item_mngr.reg_id
     *
     * @param regId the value for report_item_mngr.reg_id
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setRegId(String regId) {
        this.regId = regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item_mngr.reg_time
     *
     * @return the value of report_item_mngr.reg_time
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item_mngr.reg_time
     *
     * @param regTime the value for report_item_mngr.reg_time
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_item_mngr.item_desc
     *
     * @return the value of report_item_mngr.item_desc
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_item_mngr.item_desc
     *
     * @param itemDesc the value for report_item_mngr.item_desc
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }
}