package kr.ch.oe.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReportItemHistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public ReportItemHistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReportItemHistSeqIsNull() {
            addCriterion("report_item_hist_seq is null");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqIsNotNull() {
            addCriterion("report_item_hist_seq is not null");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqEqualTo(Long value) {
            addCriterion("report_item_hist_seq =", value, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqNotEqualTo(Long value) {
            addCriterion("report_item_hist_seq <>", value, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqGreaterThan(Long value) {
            addCriterion("report_item_hist_seq >", value, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("report_item_hist_seq >=", value, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqLessThan(Long value) {
            addCriterion("report_item_hist_seq <", value, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqLessThanOrEqualTo(Long value) {
            addCriterion("report_item_hist_seq <=", value, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqIn(List<Long> values) {
            addCriterion("report_item_hist_seq in", values, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqNotIn(List<Long> values) {
            addCriterion("report_item_hist_seq not in", values, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqBetween(Long value1, Long value2) {
            addCriterion("report_item_hist_seq between", value1, value2, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andReportItemHistSeqNotBetween(Long value1, Long value2) {
            addCriterion("report_item_hist_seq not between", value1, value2, "reportItemHistSeq");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNull() {
            addCriterion("item_code is null");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNotNull() {
            addCriterion("item_code is not null");
            return (Criteria) this;
        }

        public Criteria andItemCodeEqualTo(Long value) {
            addCriterion("item_code =", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotEqualTo(Long value) {
            addCriterion("item_code <>", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThan(Long value) {
            addCriterion("item_code >", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("item_code >=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThan(Long value) {
            addCriterion("item_code <", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThanOrEqualTo(Long value) {
            addCriterion("item_code <=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeIn(List<Long> values) {
            addCriterion("item_code in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotIn(List<Long> values) {
            addCriterion("item_code not in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeBetween(Long value1, Long value2) {
            addCriterion("item_code between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotBetween(Long value1, Long value2) {
            addCriterion("item_code not between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemValueIsNull() {
            addCriterion("item_value is null");
            return (Criteria) this;
        }

        public Criteria andItemValueIsNotNull() {
            addCriterion("item_value is not null");
            return (Criteria) this;
        }

        public Criteria andItemValueEqualTo(Long value) {
            addCriterion("item_value =", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotEqualTo(Long value) {
            addCriterion("item_value <>", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueGreaterThan(Long value) {
            addCriterion("item_value >", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueGreaterThanOrEqualTo(Long value) {
            addCriterion("item_value >=", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLessThan(Long value) {
            addCriterion("item_value <", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLessThanOrEqualTo(Long value) {
            addCriterion("item_value <=", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueIn(List<Long> values) {
            addCriterion("item_value in", values, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotIn(List<Long> values) {
            addCriterion("item_value not in", values, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueBetween(Long value1, Long value2) {
            addCriterion("item_value between", value1, value2, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotBetween(Long value1, Long value2) {
            addCriterion("item_value not between", value1, value2, "itemValue");
            return (Criteria) this;
        }

        public Criteria andReportSeqIsNull() {
            addCriterion("report_seq is null");
            return (Criteria) this;
        }

        public Criteria andReportSeqIsNotNull() {
            addCriterion("report_seq is not null");
            return (Criteria) this;
        }

        public Criteria andReportSeqEqualTo(Long value) {
            addCriterion("report_seq =", value, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqNotEqualTo(Long value) {
            addCriterion("report_seq <>", value, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqGreaterThan(Long value) {
            addCriterion("report_seq >", value, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("report_seq >=", value, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqLessThan(Long value) {
            addCriterion("report_seq <", value, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqLessThanOrEqualTo(Long value) {
            addCriterion("report_seq <=", value, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqIn(List<Long> values) {
            addCriterion("report_seq in", values, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqNotIn(List<Long> values) {
            addCriterion("report_seq not in", values, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqBetween(Long value1, Long value2) {
            addCriterion("report_seq between", value1, value2, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andReportSeqNotBetween(Long value1, Long value2) {
            addCriterion("report_seq not between", value1, value2, "reportSeq");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNull() {
            addCriterion("reg_time is null");
            return (Criteria) this;
        }

        public Criteria andRegTimeIsNotNull() {
            addCriterion("reg_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegTimeEqualTo(Date value) {
            addCriterion("reg_time =", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotEqualTo(Date value) {
            addCriterion("reg_time <>", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThan(Date value) {
            addCriterion("reg_time >", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("reg_time >=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThan(Date value) {
            addCriterion("reg_time <", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeLessThanOrEqualTo(Date value) {
            addCriterion("reg_time <=", value, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeIn(List<Date> values) {
            addCriterion("reg_time in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotIn(List<Date> values) {
            addCriterion("reg_time not in", values, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeBetween(Date value1, Date value2) {
            addCriterion("reg_time between", value1, value2, "regTime");
            return (Criteria) this;
        }

        public Criteria andRegTimeNotBetween(Date value1, Date value2) {
            addCriterion("reg_time not between", value1, value2, "regTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_item_hist
     *
     * @mbggenerated do_not_delete_during_merge Thu May 07 16:33:42 KST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_item_hist
     *
     * @mbggenerated Thu May 07 16:33:42 KST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}