package kr.ch.oe.model;

import java.util.Date;

public class ReportItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_items.report_items_seq
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private Long reportItemsSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_items.report_items_code
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private String reportItemsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_items.report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private Long reportItems;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_items.use_flag
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private String useFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_items.reg_id
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_items.reg_time
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_items.report_items_seq
     *
     * @return the value of report_items.report_items_seq
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Long getReportItemsSeq() {
        return reportItemsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_items.report_items_seq
     *
     * @param reportItemsSeq the value for report_items.report_items_seq
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setReportItemsSeq(Long reportItemsSeq) {
        this.reportItemsSeq = reportItemsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_items.report_items_code
     *
     * @return the value of report_items.report_items_code
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getReportItemsCode() {
        return reportItemsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_items.report_items_code
     *
     * @param reportItemsCode the value for report_items.report_items_code
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setReportItemsCode(String reportItemsCode) {
        this.reportItemsCode = reportItemsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_items.report_items
     *
     * @return the value of report_items.report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Long getReportItems() {
        return reportItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_items.report_items
     *
     * @param reportItems the value for report_items.report_items
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setReportItems(Long reportItems) {
        this.reportItems = reportItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_items.use_flag
     *
     * @return the value of report_items.use_flag
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_items.use_flag
     *
     * @param useFlag the value for report_items.use_flag
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_items.reg_id
     *
     * @return the value of report_items.reg_id
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_items.reg_id
     *
     * @param regId the value for report_items.reg_id
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setRegId(String regId) {
        this.regId = regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_items.reg_time
     *
     * @return the value of report_items.reg_time
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_items.reg_time
     *
     * @param regTime the value for report_items.reg_time
     *
     * @mbggenerated Sun Mar 22 14:28:40 KST 2015
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}