package kr.ch.oe.model;

import java.util.Date;

public class StudyStatus {

	@Override
	public String toString() {
		return "StudyStatus [studyStatusSeq=" + studyStatusSeq + ", userId="
				+ userId + ", eduSeq=" + eduSeq + ", studyDate=" + studyDate
				+ ", studyUnit=" + studyUnit + ", state=" + state + ", regId="
				+ regId + ", regTime=" + regTime + "]";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.study_status_seq
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private Long studyStatusSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.user_id
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.edu_seq
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private Long eduSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.study_date
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private String studyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.study_unit
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private Integer studyUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.state
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.reg_id
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private String regId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_status.reg_time
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.study_status_seq
	 * @return  the value of study_status.study_status_seq
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public Long getStudyStatusSeq() {
		return studyStatusSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.study_status_seq
	 * @param studyStatusSeq  the value for study_status.study_status_seq
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setStudyStatusSeq(Long studyStatusSeq) {
		this.studyStatusSeq = studyStatusSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.user_id
	 * @return  the value of study_status.user_id
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.user_id
	 * @param userId  the value for study_status.user_id
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.edu_seq
	 * @return  the value of study_status.edu_seq
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public Long getEduSeq() {
		return eduSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.edu_seq
	 * @param eduSeq  the value for study_status.edu_seq
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setEduSeq(Long eduSeq) {
		this.eduSeq = eduSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.study_date
	 * @return  the value of study_status.study_date
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public String getStudyDate() {
		return studyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.study_date
	 * @param studyDate  the value for study_status.study_date
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setStudyDate(String studyDate) {
		this.studyDate = studyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.study_unit
	 * @return  the value of study_status.study_unit
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public Integer getStudyUnit() {
		return studyUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.study_unit
	 * @param studyUnit  the value for study_status.study_unit
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setStudyUnit(Integer studyUnit) {
		this.studyUnit = studyUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.state
	 * @return  the value of study_status.state
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.state
	 * @param state  the value for study_status.state
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.reg_id
	 * @return  the value of study_status.reg_id
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public String getRegId() {
		return regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.reg_id
	 * @param regId  the value for study_status.reg_id
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setRegId(String regId) {
		this.regId = regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_status.reg_time
	 * @return  the value of study_status.reg_time
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_status.reg_time
	 * @param regTime  the value for study_status.reg_time
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
}