package kr.ch.oe.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudyStatusExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public StudyStatusExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStudyStatusSeqIsNull() {
			addCriterion("study_status_seq is null");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqIsNotNull() {
			addCriterion("study_status_seq is not null");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqEqualTo(Long value) {
			addCriterion("study_status_seq =", value, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqNotEqualTo(Long value) {
			addCriterion("study_status_seq <>", value, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqGreaterThan(Long value) {
			addCriterion("study_status_seq >", value, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("study_status_seq >=", value, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqLessThan(Long value) {
			addCriterion("study_status_seq <", value, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqLessThanOrEqualTo(Long value) {
			addCriterion("study_status_seq <=", value, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqIn(List<Long> values) {
			addCriterion("study_status_seq in", values, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqNotIn(List<Long> values) {
			addCriterion("study_status_seq not in", values, "studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqBetween(Long value1, Long value2) {
			addCriterion("study_status_seq between", value1, value2,
					"studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andStudyStatusSeqNotBetween(Long value1, Long value2) {
			addCriterion("study_status_seq not between", value1, value2,
					"studyStatusSeq");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andEduSeqIsNull() {
			addCriterion("edu_seq is null");
			return (Criteria) this;
		}

		public Criteria andEduSeqIsNotNull() {
			addCriterion("edu_seq is not null");
			return (Criteria) this;
		}

		public Criteria andEduSeqEqualTo(Long value) {
			addCriterion("edu_seq =", value, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqNotEqualTo(Long value) {
			addCriterion("edu_seq <>", value, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqGreaterThan(Long value) {
			addCriterion("edu_seq >", value, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqGreaterThanOrEqualTo(Long value) {
			addCriterion("edu_seq >=", value, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqLessThan(Long value) {
			addCriterion("edu_seq <", value, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqLessThanOrEqualTo(Long value) {
			addCriterion("edu_seq <=", value, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqIn(List<Long> values) {
			addCriterion("edu_seq in", values, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqNotIn(List<Long> values) {
			addCriterion("edu_seq not in", values, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqBetween(Long value1, Long value2) {
			addCriterion("edu_seq between", value1, value2, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andEduSeqNotBetween(Long value1, Long value2) {
			addCriterion("edu_seq not between", value1, value2, "eduSeq");
			return (Criteria) this;
		}

		public Criteria andStudyDateIsNull() {
			addCriterion("study_date is null");
			return (Criteria) this;
		}

		public Criteria andStudyDateIsNotNull() {
			addCriterion("study_date is not null");
			return (Criteria) this;
		}

		public Criteria andStudyDateEqualTo(String value) {
			addCriterion("study_date =", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateNotEqualTo(String value) {
			addCriterion("study_date <>", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateGreaterThan(String value) {
			addCriterion("study_date >", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateGreaterThanOrEqualTo(String value) {
			addCriterion("study_date >=", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateLessThan(String value) {
			addCriterion("study_date <", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateLessThanOrEqualTo(String value) {
			addCriterion("study_date <=", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateLike(String value) {
			addCriterion("study_date like", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateNotLike(String value) {
			addCriterion("study_date not like", value, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateIn(List<String> values) {
			addCriterion("study_date in", values, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateNotIn(List<String> values) {
			addCriterion("study_date not in", values, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateBetween(String value1, String value2) {
			addCriterion("study_date between", value1, value2, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyDateNotBetween(String value1, String value2) {
			addCriterion("study_date not between", value1, value2, "studyDate");
			return (Criteria) this;
		}

		public Criteria andStudyUnitIsNull() {
			addCriterion("study_unit is null");
			return (Criteria) this;
		}

		public Criteria andStudyUnitIsNotNull() {
			addCriterion("study_unit is not null");
			return (Criteria) this;
		}

		public Criteria andStudyUnitEqualTo(Integer value) {
			addCriterion("study_unit =", value, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitNotEqualTo(Integer value) {
			addCriterion("study_unit <>", value, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitGreaterThan(Integer value) {
			addCriterion("study_unit >", value, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitGreaterThanOrEqualTo(Integer value) {
			addCriterion("study_unit >=", value, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitLessThan(Integer value) {
			addCriterion("study_unit <", value, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitLessThanOrEqualTo(Integer value) {
			addCriterion("study_unit <=", value, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitIn(List<Integer> values) {
			addCriterion("study_unit in", values, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitNotIn(List<Integer> values) {
			addCriterion("study_unit not in", values, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitBetween(Integer value1, Integer value2) {
			addCriterion("study_unit between", value1, value2, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStudyUnitNotBetween(Integer value1, Integer value2) {
			addCriterion("study_unit not between", value1, value2, "studyUnit");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("state like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("state not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andRegIdIsNull() {
			addCriterion("reg_id is null");
			return (Criteria) this;
		}

		public Criteria andRegIdIsNotNull() {
			addCriterion("reg_id is not null");
			return (Criteria) this;
		}

		public Criteria andRegIdEqualTo(String value) {
			addCriterion("reg_id =", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotEqualTo(String value) {
			addCriterion("reg_id <>", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdGreaterThan(String value) {
			addCriterion("reg_id >", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdGreaterThanOrEqualTo(String value) {
			addCriterion("reg_id >=", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLessThan(String value) {
			addCriterion("reg_id <", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLessThanOrEqualTo(String value) {
			addCriterion("reg_id <=", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLike(String value) {
			addCriterion("reg_id like", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotLike(String value) {
			addCriterion("reg_id not like", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdIn(List<String> values) {
			addCriterion("reg_id in", values, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotIn(List<String> values) {
			addCriterion("reg_id not in", values, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdBetween(String value1, String value2) {
			addCriterion("reg_id between", value1, value2, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotBetween(String value1, String value2) {
			addCriterion("reg_id not between", value1, value2, "regId");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNull() {
			addCriterion("reg_time is null");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNotNull() {
			addCriterion("reg_time is not null");
			return (Criteria) this;
		}

		public Criteria andRegTimeEqualTo(Date value) {
			addCriterion("reg_time =", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotEqualTo(Date value) {
			addCriterion("reg_time <>", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThan(Date value) {
			addCriterion("reg_time >", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_time >=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThan(Date value) {
			addCriterion("reg_time <", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThanOrEqualTo(Date value) {
			addCriterion("reg_time <=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeIn(List<Date> values) {
			addCriterion("reg_time in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotIn(List<Date> values) {
			addCriterion("reg_time not in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeBetween(Date value1, Date value2) {
			addCriterion("reg_time between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotBetween(Date value1, Date value2) {
			addCriterion("reg_time not between", value1, value2, "regTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table study_status
	 * @mbggenerated  Mon Jan 26 11:08:52 KST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table study_status
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 26 10:06:48 KST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}